### ISSUE TITLE
Method method not regestered

### ISSUE THREAD

**Issue by HelloWorld77777777** [juliantang324/NexusSplats#2]
Excellent work! 
When I tried to evaluate sacre-coeur, I faced a problem that "Method method not registered"
Could you give me some advice at your convenient time?
Thanks for your help
![粘贴的图像](https://github.com/user-attachments/assets/3f103061-bdbd-4a3c-83fc-4ce08bfa9c1e)

**Comment by juliantang324** [comment]
Thank you for your interest in this repository and for bringing this issue to my attention!

I’ve identified the bug and resolved it in the latest version of the codebase. To address your issue, you have two options:
1. Clone the updated NexusSplats repository and train your model from scratch.
2. Alternatively, if you’d like to continue using your existing checkpoint, locate the nb-info.json file in your checkpoint directory and modify the {"method": "method"} entry to {"method": "nexus-splats"}.

I appreciate your patience and your support for this work. Please feel free to share any further feedback or ideas as you explore the project. I’m excited to see how the community utilizes and builds upon this framework—let’s make it even better together! 😊

**Comment by HelloWorld77777777** [comment]
Thank you so much for your prompt and helpful solution! Your expertise has been invaluable in resolving my issue. I appreciate your time and support.！🙂
